### ISSUE TITLE
激动搓手

### ISSUE THREAD

**Issue by KainingYing** [zeroQiaoba/gpt4v-emotion#1]
作者大大快开源

**Comment by zeroQiaoba** [comment]
Thanks very much for your attention. We will release our evaluation code, evaluation results, and paper as soon as possible.

**Comment by zeroQiaoba** [comment]
Code and data have been released.

**Comment by KainingYing** [comment]
can you provide the data?

**Comment by zeroQiaoba** [comment]
Raw data may require permission from the original author of the paper. But for the MER2023 dataset, it's a dataset that we published previously. You can apply by sending EULA to lianzheng2016@ia.ac.cn. More details can be found at https://github.com/zeroQiaoba/MER2023-Baseline.
